FROM python:3.11

ARG GNUHEALTH_SAO_PORT=8091
ARG GNUHEALTH_WEBDEV_PORT=8085
ARG GNUHEALTH_FHIR_PORT=8020

RUN apt-get update
RUN apt-get -y install --no-install-recommends vim wget npm uwsgi uwsgi-plugin-python3 python3-pip postgresql-client
RUN pip3 install psycopg2 pylibjpeg pylibjpeg-libjpeg pylibjpeg-openjpeg pyjpegls pylibjpeg-rle
RUN pip3 install pyorthanc

RUN adduser gnuhealth
USER gnuhealth

# Install gnuhealth
WORKDIR /home/gnuhealth
RUN wget -qO- https://ftp.gnu.org/gnu/health/gnuhealth-latest.tar.gz | tar -xzvf -

# GNU Health 4.4+ stores modules under his/tryton/; gnuhealth-setup expects health* at the root.
RUN GH_DIR=$(ls -d gnuhealth-* | head -1) && \
    cd "/home/gnuhealth/${GH_DIR}" && \
    for mod in his/tryton/health*; do ln -sf "${mod}" "$(basename "${mod}")"; done && \
    wget -qO- https://ftp.gnu.org/gnu/health/gnuhealth-setup-latest.tar.gz | tar -xzvf - && \
    bash ./gnuhealth-setup install

# Write gnuhealth configuration file
RUN echo "[database]\n\
path = /home/gnuhealth/attach\n\
\n\
[web]\n\
listen = *:${GNUHEALTH_SAO_PORT}\n\
root=/home/gnuhealth/sao\n\
\n\
[webdav]\n\
listen = *:${GNUHEALTH_WEBDEV_PORT}\n\
ssl_webdav = False\n" > /home/gnuhealth/gnuhealth/tryton/server/config/trytond.conf

# Install sao
WORKDIR /home/gnuhealth
RUN wget -qO- https://downloads.tryton.org/6.0/tryton-sao-6.0.45.tgz | tar -xzvf -
RUN mv package sao
WORKDIR /home/gnuhealth/sao
RUN npm install --production --legacy-peer-deps


WORKDIR /home/gnuhealth

# Install FHIR server
RUN pip3 install --upgrade --user gnuhealth-fhir-server
COPY fhir-config.py /home/gnuhealth/.local/lib/python3.11/site-packages/fhir_server/config.py

# Write FHIR server configuration file
RUN echo "[uwsgi]\n\
master = true\n\
processes = 5\n\
plugins = python3\n\
http-socket=0.0.0.0:${GNUHEALTH_FHIR_PORT}\n\
module=fhir_uwsgi:app\n\
logto = /tmp/fhir_server.log\n" > /home/gnuhealth/.local/lib/python3.11/site-packages/fhir_server/server_uwsgi.ini

EXPOSE ${GNUHEALTH_SAO_PORT}
EXPOSE ${GNUHEALTH_WEBDEV_PORT}
EXPOSE ${GNUHEALTH_FHIR_PORT}

# Define environment variable
ENV NAME=GNUHealth_Fhir_Server
